### ISSUE TITLE
Hide MapBox API token

### ISSUE THREAD

**Issue by akilhylton** [COVID-19-electronic-health-system/decentralized-electronic-health-record#12]
Resource: https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by renegmed** [comment]
to make this work, from root add 2 files .env and env.development with similar content 
 REACT_APP_MAPBOX_TOKEN='pk.eyJ1IjoiYWh5bHRvbjE5IiwiYSI6ImNrN3FrYnFxOTAwOGUzc21jYWFtNzh4aG4ifQ.mXUbDQrYWm7TnEexZJ4f1Q'

Then in App.js change  DEMO_API_KEY with 
DEMO_API_KEY = process.env.REACT_APP_MAPBOX_TOKEN; 

Finally on .gitignore, add the following

.env
.env.development
