### ISSUE TITLE
Decide on Database

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/decentralized-electronic-health-record#7]
In hopes of an IPR Monday, March 16, I feel like we should settle on a database to use for this application. Some suggestions discussed so far in the [Discord](https://discord.gg/BEz3Eb) have been Mongo, Blockstack (using [Radikis](https://github.com/blockstack/radiks) on top of Blockstack storage, I think), and PostGIS (a database extender for Postgres).

I don't have extensive knowledge into decentralized apps, nor have I worked with PostGIS before, so I will leave my recommendation and two cents for Mongo. From my experience, it is exceedingly easy to get something spun up _very_ quickly using [MongoDB Atlas](https://www.mongodb.com/cloud/atlas). It being a NoSQL database means that we can easily alter the data we have in our database without having to worry about a strict schema that would constantly need updating/changing. 

Let's discuss below!

**Comment by jmsmdy** [comment]
Using Django, database migrations with PostGIS can be handled automatically when the schema changes. The advantage of PostGIS is that it scales well for handling the type of queries we'd be doing (e.g., finding if two people crossed paths at a certain time).

**Comment by SomeMoosery** [comment]
Cool, I had forgotten about that feature until you just mentioned it! I'm going to make another issue regarding what we want to use on the backend as well. If we end up deciding on using a different backend technology, I wonder how that will affect working with PostGIS.

It seems like a lot of people (myself included) have more experience with JS/Express/Node, so I can do some research into how those two could work together if we end up going with a different backend language, but still use PostGIS.

**Comment by KerronManwaring** [comment]
A smart contract on ethereum as the backend?

**Comment by tesla809** [comment]
solved with a commit by @jmsmdy
